base_model: Qwen/Qwen2-7B
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer
is_llama_derived_model: false

load_in_8bit: false
load_in_4bit: true
strict: false

datasets:
  - path: ../bin/train_data/cd_ls.jsonl
    ds_type: json
    type: completion
    field: text
  - path: ../bin/train_data/terminal_log.jsonl
    ds_type: json
    type: completion
    field: text

dataset_prepared_path: ./prepared_data
val_set_size: 0.05
output_dir: ./qwen-finetuned

sequence_len: 2048
sample_packing: true
pad_to_sequence_len: true

adapter: lora
lora_model_dir:
lora_r: 8
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules:
  - c_attn
  - c_proj

wandb_project: qwen-finetune
wandb_entity:
wandb_watch:
wandb_run_id:
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 2
num_epochs: 3
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002
train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: true

warmup_steps: 10
eval_steps: 50
save_steps: 50
