base_model: Qwen/Qwen2-1.5B
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer
is_llama_derived_model: false

load_in_8bit: true
load_in_4bit: false
strict: false

datasets:
  - path: ../bin/train_data/terminal_log.jsonl
    ds_type: json
    type: completion
    field: text
    num_proc: 16  # adjust based on your available CPU cores


dataset_prepared_path: ./prepared_data
val_set_size: 0.05
output_dir: ./qwen-1.5b-finetuned

sequence_len: 512
sample_packing: true
pad_to_sequence_len: true

adapter: lora
lora_model_dir:
lora_r: 8
lora_alpha: 32
lora_dropout: 0.05
lora_target_modules:
  - q_proj
  - k_proj
  - v_proj
  - o_proj

wandb_project: qwen-finetune
wandb_entity:
wandb_watch:
wandb_run_id:
wandb_log_model:

gradient_accumulation_steps: 2
micro_batch_size: 2
num_epochs: 3
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002
train_on_inputs: false
group_by_length: true
bf16: auto
fp16: false
tf32: true

warmup_steps: 100
eval_steps: 100
save_steps: 100

gradient_checkpointing: true
flash_attention: true
