#!/usr/bin/env python3
"""tests/fuzz/llvm_signedness_fuzz.py — randomized ELEMENT-SIGNEDNESS programs
for the LLVM lane, with a by-construction oracle.

WHY A SECOND GENERATOR
----------------------
tests/fuzz/adder_fuzzer.py's main() reliably bails the SSA subset (SBR_MEMORY:
2-D array globals, float traffic, ...), so the LLVM lane emits no @main for it
and every program comes back "unsupported". A differential that can never run
a program is not an instrument. This generator emits SMALL, SSA-subset-clean
programs whose ONLY subject is the decision that shipped a miscompile to all
272 LLVM-lane apps: is the value produced by

    p[i]                      p a Ptr[T] PARAMETER
    cast[Ptr[T]](a)[i]        ND_CAST index base
    fn(a)[i]                  ND_CALL index base
    h[0].f  /  h[0].pf[i]     ND_MEMBER through a Ptr[Struct] parameter
    cast[T](x)                ND_CAST value

signed or unsigned?  ssa.ad's ssa_expr_sgn answered "unknown" for most of
those, and the two consumers read "unknown" in OPPOSITE directions --
shift/div/mod as UNSIGNED, ordered compare as SIGNED -- so an unresolved base
is wrong both ways at once and neither says so.  Every value this generator
plants has its HIGH BIT SET (or is negative), which is the only regime in
which the signed and unsigned instruction differ at all; with small positive
values the whole bug class is invisible, which is precisely why a decade of
green fuzz runs meant nothing here.

Every result is folded into a single uint64 accumulator predicted exactly in
Python, so a wrong instruction changes the printed number.

Usage (as a module):
    src, expected_stdout, expected_exit = gen(seed)
"""
import random

MASK64 = (1 << 64) - 1


class T:
    def __init__(self, name, bits, signed):
        self.name, self.bits, self.signed = name, bits, signed

    def wrap(self, v):
        """Value as this type sees it (sign-extended for signed types)."""
        v &= (1 << self.bits) - 1
        if self.signed and v >= (1 << (self.bits - 1)):
            v -= 1 << self.bits
        return v


TYPES = [T("int8", 8, True), T("uint8", 8, False),
         T("int16", 16, True), T("uint16", 16, False),
         T("int32", 32, True), T("uint32", 32, False),
         T("int64", 64, True), T("uint64", 64, False)]


def _reg(v):
    """64-bit register view of a Python int (two's complement)."""
    return v & MASK64


def gen(seed):
    rng = random.Random(seed)
    L = []
    acc = 0

    def fold(expr, val):
        nonlocal acc
        L.append(f"    g_acc = g_acc + ({expr})")
        acc = (acc + (val & MASK64)) & MASK64

    top = []
    top.append("# AUTO-GENERATED by tests/fuzz/llvm_signedness_fuzz.py "
               "-- do not edit.")
    top.append("extern def sys_write(fd: int32, buf: Ptr[uint8], "
               "count: uint64) -> int64")
    top.append("")
    top.append("g_acc: uint64")
    top.append("gd: Array[32, uint8]")
    top.append("gc: Array[1, uint8]")
    for t in TYPES:
        top.append(f"gb_{t.name}: Array[8, {t.name}]")
    top.append("")
    top.append("class SBox:")
    top.append("    pf: Ptr[int64]")
    top.append("    sc: int64")
    top.append("")
    top.append("gpf: Array[8, int64]")
    top.append("")
    # print helper (mirrors the differential fuzzer's PRELUDE shape)
    top += [
        "def putc(c: uint8) -> int32:",
        "    gc[0] = c",
        "    sys_write(cast[int32](1), &gc[0], cast[uint64](1))",
        "    return 0",
        "",
        "def print_acc(val: uint64) -> int32:",
        "    nd: int64 = 0",
        "    v: uint64 = val",
        "    if v == cast[uint64](0):",
        "        gd[0] = cast[uint8](48)",
        "        nd = 1",
        "    while v > cast[uint64](0):",
        "        q: uint64 = v / cast[uint64](10)",
        "        d: uint64 = v - q * cast[uint64](10)",
        "        gd[cast[int64](nd)] = cast[uint8](d + cast[uint64](48))",
        "        nd = nd + 1",
        "        v = q",
        "    k: int64 = nd - 1",
        "    while k >= 0:",
        "        putc(gd[cast[int64](k)])",
        "        k = k - 1",
        "    putc(cast[uint8](10))",
        "    return 0",
        "",
    ]
    # per-type probe helpers: the BASE KIND is the subject, so each takes its
    # buffer as a PARAMETER and never touches a global.
    for t in TYPES:
        n = t.name
        top += [
            f"def shr_p_{n}(p: Ptr[{n}], i: uint64, s: {n}) -> uint64:",
            f"    return cast[uint64](cast[{n}](p[i] >> s))",
            "",
            f"def cmp_p_{n}(p: Ptr[{n}], i: uint64, k: {n}) -> uint64:",
            f"    if p[i] < k:",
            f"        return cast[uint64](1)",
            f"    return cast[uint64](0)",
            "",
            f"def shr_castb_{n}(a: uint64, i: uint64, s: {n}) -> uint64:",
            f"    return cast[uint64](cast[{n}](cast[Ptr[{n}]](a)[i] >> s))",
            "",
            f"def mkp_{n}(a: uint64) -> Ptr[{n}]:",
            f"    return cast[Ptr[{n}]](a)",
            "",
            f"def shr_callb_{n}(a: uint64, i: uint64, s: {n}) -> uint64:",
            f"    return cast[uint64](cast[{n}](mkp_{n}(a)[i] >> s))",
            "",
            f"def cast_val_{n}(x: uint64, s: {n}) -> uint64:",
            f"    return cast[uint64](cast[{n}](cast[{n}](x) >> s))",
            "",
        ]
    top += [
        "def div_p(p: Ptr[int64], i: uint64, d: int64) -> int64:",
        "    return p[i] / d",
        "",
        "def mod_p(p: Ptr[int64], i: uint64, d: int64) -> int64:",
        "    return p[i] % d",
        "",
        "def msc(h: Ptr[SBox], s: int64) -> int64:",
        "    return h[0].sc >> s",
        "",
        "def mfa(h: Ptr[SBox], i: uint64, s: int64) -> int64:",
        "    return h[0].pf[i] >> s",
        "",
    ]

    L.append("def main(argc: int32, argv: Ptr[uint64]) -> int32:")
    L.append("    g_acc = cast[uint64](0)")

    for t in TYPES:
        n, bits = t.name, t.bits
        hi = 1 << (bits - 1)
        idx = rng.randrange(8)
        raw = hi | rng.randrange(hi)             # HIGH BIT SET
        L.append(f"    gb_{n}[{idx}] = cast[{n}]({raw})")
        val = t.wrap(raw)                        # type-view value
        ubits = raw & ((1 << bits) - 1)          # raw bit pattern
        L.append(f"    a_{n}: uint64 = cast[uint64](&gb_{n}[0])")
        s = rng.randint(1, bits - 1)
        want = t.wrap((val >> s) if t.signed else (ubits >> s))
        sh = f"cast[{n}]({s})"
        for fn in (f"shr_p_{n}(cast[Ptr[{n}]](a_{n}), cast[uint64]({idx}), {sh})",
                   f"shr_castb_{n}(a_{n}, cast[uint64]({idx}), {sh})",
                   f"shr_callb_{n}(a_{n}, cast[uint64]({idx}), {sh})"):
            fold(fn, _reg(want))
        # cast[T](x) >> s on a bit-63/high-bit-set operand
        fold(f"cast_val_{n}(cast[uint64]({raw}), {sh})", _reg(want))
        # ordered compare against a value with the high bit CLEAR, so the
        # signed and unsigned answers genuinely disagree.
        k = rng.randrange(hi)
        res = 1 if ((val < t.wrap(k)) if t.signed else (ubits < k)) else 0
        fold(f"cmp_p_{n}(cast[Ptr[{n}]](a_{n}), cast[uint64]({idx}), "
             f"cast[{n}]({k}))", res)

    # signed div/mod through a Ptr[int64] parameter, NEGATIVE dividend
    di = rng.randrange(8)
    dv = -rng.randint(1, 1 << 40)
    L.append(f"    gpf[{di}] = cast[int64](0 - {-dv})")
    L.append("    ap: uint64 = cast[uint64](&gpf[0])")
    den = rng.choice([3, 5, 7, 13, 97])
    q = -((-dv) // den)                          # truncate toward zero
    r = dv - q * den
    fold(f"cast[uint64](div_p(cast[Ptr[int64]](ap), cast[uint64]({di}), "
         f"cast[int64]({den})))", _reg(q))
    fold(f"cast[uint64](mod_p(cast[Ptr[int64]](ap), cast[uint64]({di}), "
         f"cast[int64]({den})))", _reg(r))

    # struct field + field-array through a Ptr[SBox] parameter, negative
    sc = -rng.randint(1, 1 << 40)
    ss = rng.randint(1, 20)
    L.append("    bx: SBox")
    L.append("    bx.pf = cast[Ptr[int64]](ap)")
    L.append(f"    bx.sc = cast[int64](0 - {-sc})")
    fold(f"cast[uint64](msc(&bx, cast[int64]({ss})))", _reg(sc >> ss))
    fold(f"cast[uint64](mfa(&bx, cast[uint64]({di}), cast[int64]({ss})))",
         _reg(dv >> ss))

    L.append("    print_acc(g_acc)")
    L.append("    return cast[int32](g_acc & cast[uint64](255))")

    src = "\n".join(top) + "\n" + "\n".join(L) + "\n"
    return src, str(acc & MASK64), acc & 0xFF


if __name__ == "__main__":
    import sys
    s, out, ex = gen(int(sys.argv[1]) if len(sys.argv) > 1 else 1)
    if len(sys.argv) > 2:
        open(sys.argv[2], "w").write(s)
        print(f"{out} {ex}")
    else:
        sys.stdout.write(s)
